import Head from "next/head";
import ExploreCreate from "../components/Home/ExploreCreate";
import NextInitialDrops from "../components/Home/NextInitialDrops";
import HomeNFTs from "../components/Home/HomeNFTs";
import { useMediaQuery } from "react-responsive";
import { useEffect, useState } from "react";
import Footer from "../components/Layout/Footer";
import Translate, { useTranslate } from "../components/Text/Translate";

interface HomeProps {}

const Home: React.FC<HomeProps> = () => {
  const [big, setBig] = useState<boolean>(false);

  const isBigScreen = useMediaQuery({ query: "(min-width: 900px)" });

  useEffect(() => {
    setBig(isBigScreen);
  }, [isBigScreen]);

  return (
    <>
      <Head>
        <title>{useTranslate("home_title")}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <ExploreCreate isBigScreen={big} />
      {/* <NextInitialDrops isBigScreen={big} /> */}
      <HomeNFTs isBigScreen={big} />
      <Footer />
    </>
  );
};

export default Home;
